//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class CatetoryType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatetoryType()
        {
            this.Categories = new HashSet<Category>();
            this.createdDate = DateTime.Now.Date;

        }

        [HiddenInput(DisplayValue = false)]
        public int categoryTypeID { get; set; }
        [Display(Name = "Category Type Name")]
        public string categoryTypeName { get; set; }
        [Display(Name = "Category Type Description")]
        public string categoryTypeDescription { get; set; }
        [Display(Name = "Created Name")]
        public System.DateTime createdDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}

