//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.TransactionLogs = new HashSet<TransactionLog>();
            this.createdDate = DateTime.Now.Date;
        }
        [HiddenInput(DisplayValue = false)]
        public int categoryId { get; set; }
        [DisplayName("Category Name")]
        public string categoryName { get; set; }
        [DisplayName("Category Description")]
        public string categoryDescription { get; set; }
        [HiddenInput(DisplayValue = false)]
        public int categoryTypeId { get; set; }
        
        public System.DateTime createdDate { get; set; }
    
        public virtual CatetoryType CatetoryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionLog> TransactionLogs { get; set; }
    }
}
